# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 632baf20955abb2a198357b5e401bec510e7a7ebe67c0e97daf76e5eeb2f63eec7331dddab42c3b753ce950e4f08dd5e75312e3546da5d4225c5a95a08f87a8d

test:
  secret_key_base: a22698492636ce2511134a32f08a235b642f888b1d8dd42cefed972b57bb2e7aa790319e487db5d9ba4b10a03af87cf16655407b7a4125fcdb53908dcad6b235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
